spot_api_homepage:
    path:     /api
    defaults: { _controller: SpotApiBundle:Default:index }

spot_api_marker:
    resource: Codeforges\SpotRadar\SpotApiBundle\Controller\MarkerController
    type: rest