spot_api_v1:
    resource: "@SpotApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

cf_rest_v1:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

spot_auth_v2:
    resource: "@AuthServerBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc