# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
             id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api_doc:
            pattern:      ^/api/doc
            security:     false

        api:
            pattern: ^/api/v2
            fos_oauth: true
            stateless: true
            anonymous: true

    access_control:
          - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }